# Generated by Django 5.2.11 on 2026-03-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filr', models.FileField(upload_to='attachements/')),
                ('file_type', models.CharField(choices=[('txt', 'Text'), ('pdf', 'PDF'), ('img', 'Image')])),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachement', to='chat.chatmessage')),
            ],
        ),
    ]
